# Generated by Django 4.2 on 2026-03-17 01:53

import apps.screenshots.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.screenshots.models.screenshot_upload_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(default=0)),
                ('is_viewed', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='devices.device')),
            ],
            options={
                'db_table': 'screenshots',
                'ordering': ['-timestamp'],
            },
        ),
    ]
