# Generated by Django 4.2 on 2026-02-18 01:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_id', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message_type', models.CharField(choices=[('sms', 'SMS'), ('mms', 'MMS')], default='sms', max_length=20)),
                ('direction', models.CharField(choices=[('sent', 'Enviada'), ('received', 'Recebida')], max_length=20)),
                ('content', models.TextField()),
                ('mms_url', models.URLField(blank=True, null=True)),
                ('message_date', models.DateTimeField(db_index=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('original_content', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='devices.device')),
            ],
            options={
                'db_table': 'messages_sms',
                'ordering': ['-message_date'],
            },
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['device', 'message_date'], name='messages_sm_device__154c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['phone_number'], name='messages_sm_phone_n_07c059_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['thread_id'], name='messages_sm_thread__47181e_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['is_deleted'], name='messages_sm_is_dele_cea981_idx'),
        ),
    ]
