# Generated by Django 4.2 on 2026-02-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smsmessage',
            name='messages_sm_device__154c4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='smsmessage',
            name='messages_sm_phone_n_07c059_idx',
        ),
        migrations.RemoveIndex(
            model_name='smsmessage',
            name='messages_sm_thread__47181e_idx',
        ),
        migrations.RemoveIndex(
            model_name='smsmessage',
            name='messages_sm_is_dele_cea981_idx',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='mms_url',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='original_content',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='synced_at',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='thread_id',
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterModelTable(
            name='smsmessage',
            table='sms_messages',
        ),
    ]
