# Generated by Django 4.2 on 2026-02-18 01:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whatsapp_message_id', models.CharField(max_length=255, unique=True)),
                ('chat_id', models.CharField(db_index=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('is_group', models.BooleanField(default=False)),
                ('group_name', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(choices=[('sent', 'Enviada'), ('received', 'Recebida')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('document', 'Documento'), ('location', 'Localização'), ('contact', 'Contato')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_path', models.CharField(blank=True, max_length=500)),
                ('media_size', models.IntegerField(blank=True, null=True)),
                ('media_duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou')], default='sent', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('message_date', models.DateTimeField(db_index=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('original_content', models.TextField(blank=True)),
                ('quoted_message_id', models.CharField(blank=True, max_length=255)),
                ('quoted_content', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='devices.device')),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['-message_date'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(max_length=255, unique=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_group', models.BooleanField(default=False)),
                ('last_message', models.TextField(blank=True)),
                ('last_message_date', models.DateTimeField()),
                ('last_message_type', models.CharField(blank=True, max_length=20)),
                ('total_messages', models.IntegerField(default=0)),
                ('unread_count', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_muted', models.BooleanField(default=False)),
                ('mute_expiration', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_chats', to='devices.device')),
            ],
            options={
                'db_table': 'whatsapp_chats',
                'ordering': ['-last_message_date'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['device', 'message_date'], name='whatsapp_me_device__7bb1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['chat_id', 'message_date'], name='whatsapp_me_chat_id_496255_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['whatsapp_message_id'], name='whatsapp_me_whatsap_151334_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['is_deleted'], name='whatsapp_me_is_dele_250e58_idx'),
        ),
    ]
