# Generated by Django 4.2 on 2026-02-18 01:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('call_type', models.CharField(choices=[('incoming', 'Recebida'), ('outgoing', 'Realizada'), ('missed', 'Perdida'), ('rejected', 'Rejeitada'), ('blocked', 'Bloqueada')], max_length=20)),
                ('duration', models.IntegerField(default=0, help_text='Duração em segundos')),
                ('call_date', models.DateTimeField(db_index=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('sim_slot', models.IntegerField(blank=True, null=True)),
                ('imei', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='devices.device')),
            ],
            options={
                'db_table': 'calls_call',
                'ordering': ['-call_date'],
            },
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['device', 'call_date'], name='calls_call_device__ea188d_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['phone_number'], name='calls_call_phone_n_25c1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['call_type'], name='calls_call_call_ty_f1619d_idx'),
        ),
    ]
