# Generated by Django 4.2 on 2026-03-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='call',
            name='calls_call_device__ea188d_idx',
        ),
        migrations.RemoveIndex(
            model_name='call',
            name='calls_call_phone_n_25c1ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='call',
            name='calls_call_call_ty_f1619d_idx',
        ),
        migrations.RemoveField(
            model_name='call',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='call',
            name='call_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_type',
            field=models.CharField(choices=[('incoming', 'Recebida'), ('outgoing', 'Realizada'), ('missed', 'Perdida')], max_length=20),
        ),
        migrations.AlterField(
            model_name='call',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
